TT-46 changes to purchase new plan
VinsanityShred/WebAutomation pull request #8
Opened 2021-05-21 23:22 UTC by kduerksen

Configured to test purchase of two of the available plans, with code configured to expand to all programs over time

2021-06-09 23:55 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredBigArmsProgramPage.java
> +        //vsClickToPurchaseLocator = By.xpath("/html/body/main/section[17]/div/div/div/div/a");
If we don't need this commented out locator can you please just remove it.

2021-06-09 23:56 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredBigArmsProgramPage.java
> +        //vsClickToPurchaseLocator = By.xpath("/html/body/main/section[17]/div/div/div/div/a");
Also, can you add the //// Locators //// comment to define where the locators are defined.

2021-06-09 23:57 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredBigArmsProgramPage.java
> +    }
Can you move this under the //// Verifiers //// section please.

2021-06-09 23:59 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHerProgramPage.java
> +    }
Can you move this under the //// Verifiers ///// section please.

2021-06-10 00:04 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHerProgramPage.java
> +    }
Question do you need to create the login page object within a method? It can't just be defined on it's own below the   constructor?

2021-06-10 00:05 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHimProgramPage.java
> +        vsFatLossExtremeHimPage.verifyPurchaseButtonIsDisplayed();
Can you add this to the //// Verifiers //// section please.

2021-06-10 00:06 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredBigArmsProgramPage.java
> +        //vsClickToPurchaseLocator = By.xpath("/html/body/main/section[17]/div/div/div/div/a");
The purchase button locator is in the //// Locators //// section of the BaseProgramPage class, with assignment of that locator done in descendent classes (big arms, fat loss him/her, etc.) and therefore needing to be in the constructor. Yes, the commented-out locator assignment can be removed.

2021-06-10 00:06 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHimProgramPage.java
> +        vsClickToPurchaseLocator = By.xpath("/html/body/div[4]/section[29]/div/div/div[2]/div/a");
Can you add this to the //// Locators //// section please by just moving the //// Locators //// comment up.

2021-06-10 00:07 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredBigArmsProgramPage.java
> +    }
Yes, will move it to under that comment/section

2021-06-10 00:08 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHimProgramPage.java
> +    }
Same question here do we need this defined as a method and just on it own?

2021-06-10 00:09 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredPostOrderOffer_1.java
> +    }
Can you move this under the //// Verifiers //// section please.

2021-06-10 00:10 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredPostOrderOffer_1.java
> +    }
Same here can this be defined outside the method?

2021-06-10 00:11 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredProgramsPage.java
> +    }*/
Please move under the //// Verifiers //// section please.

2021-06-10 00:11 UTC, cramirez4673 commented on src/test/java/web/pages/vshred/VshredProgramsPage.java
> +    }
Same as above

2021-06-10 00:13 UTC, cramirez4673 commented on src/test/java/web/tests/vshred/VSPurchaseTest.java
> +        //VshredFatLossExtremeHerProgramPage.createVSFatLossExtremeHerPage(driver); // **NOTE**: post order offer one page different than above programs
Do we need this commented code?

2021-06-10 00:15 UTC, cramirez4673 requested changes
Please let me know if you have any questions or we need to sync.

2021-06-11 17:22 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredBigArmsProgramPage.java
> +    }
Done

2021-06-11 17:22 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHerProgramPage.java
> +    }
Done

2021-06-11 17:24 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHerProgramPage.java
> +    }
I just followed object creation methods I noted as already established in existing code when I came onto the project. This can be up for further review and change later, but I'll leave object creation in methods for now.

2021-06-11 17:24 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHimProgramPage.java
> +        vsFatLossExtremeHimPage.verifyPurchaseButtonIsDisplayed();
Done

2021-06-11 17:25 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHimProgramPage.java
> +        vsClickToPurchaseLocator = By.xpath("/html/body/div[4]/section[29]/div/div/div[2]/div/a");
Done

2021-06-11 17:25 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredFatLossExtremeHimProgramPage.java
> +    }
See comment on related question earlier in review

2021-06-11 17:26 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredPostOrderOffer_1.java
> +    }
Done

2021-06-11 17:27 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredPostOrderOffer_1.java
> +    }
See comment on first question regarding this method for object creation

2021-06-11 17:29 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredProgramsPage.java
> +    }*/
Done

2021-06-11 17:29 UTC, kduerksen commented on src/test/java/web/pages/vshred/VshredProgramsPage.java
> +    }
See first comment on similar issue

2021-06-11 17:31 UTC, kduerksen commented on src/test/java/web/tests/vshred/VSPurchaseTest.java
> +        //VshredFatLossExtremeHerProgramPage.createVSFatLossExtremeHerPage(driver); // **NOTE**: post order offer one page different than above programs
Yes, the commented-out code establishes another program that can be purchased through automated testing, though it has some variation from other purchase flows that still needs to be ironed out. Hence it is commented out for now, just to make putting that code in a bit quicker and easier in the future.

2021-06-15 15:44 UTC, merged